### ISSUE TITLE
compared to color gem

### ISSUE THREAD

**Issue by trans** [wdevauld/colour#1]
How would you say your library compares to the color gem?

  https://github.com/halostatue/color

**Comment by wdevauld** [comment]
My initial impressions are that the color library is more verbose, and contains more features.  The colour library has a smaller set of features, and was written to be tighter.

Guess it depends on what you are trying to do.  The colour library is made more for generating palettes and finding colours that work in part of a scheme.  The color library seems to be more oriented towards reading and writing several different formats, although the library also has the same algorithms for rotating around the HSV hue, as well as lightening and darkening.

**Comment by trans** [comment]
So you are actively developing/using colour I take it? The reason I ask is b/c I'm getting just shy of zero feedback from Austin Ziegler about patches to his color gem. I've started to think about a fork. Then I found your gem. Are you open to expanding it's capabilities?

**Comment by wdevauld** [comment]
Absolutely,
   My only request is that any new functionality be covered in a test.
Depending on the size of the additions, I usually review and provide
feedback/merge within a few days, at most a week.

-W

On Mon, Feb 27, 2012 at 8:26 AM, 7rans <
reply@reply.github.com

**Comment by trans** [comment]
Great! I won't be able to work on it any time in the next few days, but I'll have a look soon as I can.
